# Generated by Django 3.1.2 on 2020-11-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_siteannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteannouncement',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
