# Generated by Django 3.1.2 on 2020-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_siteannouncement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteannouncement',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
